### ISSUE TITLE
Add process outline to README

### ISSUE THREAD

**Issue by mmoga** [sharpchris/coding352#2]
Per Chris:

> Proposed plan - I’ve set up the folder convention in Github. You should create new branches for your own personal work, commit them to Github, and make a pull request to bring your work into `master`

**Comment by sharpchris** [comment]
Maybe we can also request a review for each of our pull requests, and we could do something like having a rule that you have to round-robin your reviewers so that we all are seeing each others contributions

**Comment by sharpchris** [comment]
This issue is addressed by #3
